#!/bin/sh

appname="scaffold-restapi"

port=`awk '{
    if (/server/) { is_server=1 }
    else if (/{/ && is_server>0) { is_server++ }
    else if  (/}/ && is_server>0) { is_server-- }
    else if (is_server==1) { print } }' /etc/scaffold/$appname/config.properties | grep -o '[0-9]*'`
if [ ! "$port" ]; then
  echo "Cannot work out port from /etc/$appname/config.properties" >&2
  exit 1
fi

# block the deploy script until server starts
count=0
while ! nc -vz localhost $port > /dev/null 2>&1; do
 sleep 1
 echo -n .
 count=$((count+1))
done

echo
echo "Restart took: $count seconds"